[default]
public_key = "GASUZBOCEEYODKEA6M2RYVNADFVBSANCPYNZLWXWX4IQV2IHQTSDBJQE"
secret_key = "SDZQZAIKXEKCABNLW4BMNNXOMZL5XULOQZEWRBJOGUNHGWDLLAPNFRVR"

[testnet]
public_key = "GASUZBOCEEYODKEA6M2RYVNADFVBSANCPYNZLWXWX4IQV2IHQTSDBJQE"
secret_key = "SDZQZAIKXEKCABNLW4BMNNXOMZL5XULOQZEWRBJOGUNHGWDLLAPNFRVR"